import os

appid = os.environ.get("APPID")
apikey = os.environ.get("APIKEY")
# gender = os.environ.get("GENDER")
# weight = os.environ.get("WEIGHT")
# height = os.environ.get("HEIGHT")
# age = os.environ.get("AGE")
bearertoken = os.environ.get("BEARERTOKEN")
food_sheet_name = os.environ.get("FOOD_NAME")
workout_sheet_name = os.environ.get("WORKOUT_NAME")
url_string = os.environ.get("URLSTRING")
mysql_db = os.environ.get("MYSQL_DB")
mysql_username = os.environ.get("MYSQL_USER")
mysql_pass = os.environ.get("MYSQL_PASS")
mysql_host = os.environ.get("MYSQL_HOST")
tracker_user = os.environ.get("USER_EMAIL")
